### ISSUE TITLE
permission denied for this window type

### ISSUE THREAD

**Issue by iamhabib** [PuffoCyano/mcnightmode#1]
FATAL EXCEPTION: main
                                                                       Process: com.mcsoft.mcnightmode, PID: 32251
                                                                       java.lang.RuntimeException: Unable to start service com.mcsoft.mcnightmode.NightService@a02570e with Intent { cmp=com.mcsoft.mcnightmode.NightService }: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@26bd909 -- permission denied for this window type
                                                                           at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4145)
                                                                           at android.app.ActivityThread.access$2400(ActivityThread.java:229)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                        Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@26bd909 -- permission denied for this window type
                                                                           at android.view.ViewRootImpl.setView(ViewRootImpl.java:920)
                                                                           at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:337)
                                                                           at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
                                                                           at com.dimiklab.meditest.service.NightService.a(Unknown Source)
                                                                           at com.dimiklab.meditest.service.NightService.onStartCommand(Unknown Source)
                                                                           at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4128)
                                                                           at android.app.ActivityThread.access$2400(ActivityThread.java:229) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by PuffoCyano** [comment]
Hi. Which version of android give you this error? If you run Android 8 you
have to run service with startForegroundService(new Intent(context,
NightService.class)). Keep me updated thanks

Il 22 feb 2018 11:44, "Habibur Rahman" <notifications@github.com> ha
scritto:

**Comment by PuffoCyano** [comment]
However if you have permission denied you should allow permission to draw on other apps

**Comment by iamhabib** [comment]
Sorry bro for late. I have tested using android 6.0 OS version. I should try again to use your awesome library. Thanks for your reply.

**Comment by PuffoCyano** [comment]
I hope I have solved the problem and thanks for the feedback

Il 24 feb 2018 19:03, "Habibur Rahman" <notifications@github.com> ha
scritto:
